[server]
address = ":8091"

[API]
tg_bot_token = "5024063266:AAF7X85OHvufdp46WTg1recjoYNtcCFAyo8"

[database]
address = "127.0.0.1"
port = ":5432"
name = "ton_kenguru_test"
username = "postgres"
password = "n19171540"
scheme = "postgres"
