[server]
address = ":8091"

[TelegramAPI]
bot_token = "5172772606:AAFqj0gcUXaOHySPw14pG3BbDMTuv9isowU"
bot_name = "artversebot"

[BotImplementation]
start_message = "<a href=\"https://t.me/theopenart\">The Open Art</a> совместно с <a href=\"https://t.me/theopenverse\">TON VERSE</a> проводит розыгрыш 3 NFT от проекта <a href=\"https://t.me/theopenverse\">TON VERSE</a>. \nПринять участие очень просто - выполняйте задания и получайте баллы, которые увеличивают шансы выиграть NFT.\n\n💎 Больше информации в официальном сообществе <a href=\"https://t.me/theopenart\">The Open Art</a> и в официальном сообществе <a href=\"https://t.me/theopenverse\">TON VERSE</a>."
subscribe_to_join_message = "Для участия подпишитесь на каналы <a href=\"https://t.me/theopenart\">The Open Art</a> и <a href=\"https://t.me/theopenverse\">TON VERSE</a>. Важно быть подписанным до окончания конкурса."
subscribed_to_all_message = "✨ Поздравляем! Вы участвуете в розыгрыше NFT.\nПобедитель будет объявлен 14 февраля 2022 года в 16:00. Шанс выиграть NFT напрямую зависит от баллов: чем их больше, тем выше вероятность получить NFT. Вы можете приглашать друзей: за каждую его подписку вы получите по 50 баллов (всего 100), но следите, чтобы они не отписывались, а то баллы за них учтены не будут!"

required_subscriptions = [ "@theopenart", "@theopenverse" ]

[database]
address = "127.0.0.1"
port = ":5432"
name = "ton_bot"
username = "postgres"
password = "postgres"
scheme = "postgres"
