[server]
address = ":8091"

[API]
tg_bot_token = "5072079628:AAGKVoqAvcf-MorApAOjijIFzgorcOayTJk"

[database]
address = "127.0.0.1"
port = ":5432"
name = "ton_kenguru_test"
username = "postgres"
password = "n19171540"
scheme = "postgres"
