[server]
address = ":8100"

[bot]
token = "5313561308:AAECy6OFRIm57LtB5iEq3V6USelZutwHTXk"
name = "toncells_ref_bot"
rating_limit = 100
required_subscriptions = [ "@theopenart", "@toncells" ]

[bot.messages]
start = """
💎 <a href=\"https://t.me/toncells\"><b>TonCells</b></a> проводит конкурс+розыгрыш, в котором нужно приглашать друзей!

<b>Важно, что размер приза зависит только от вас!</b>

Вам надо выполнить всего лишь 2 условия:
— Подписаться на <a href=\"https://t.me/toncells\"><b>TonCells</b></a>
— Пригласить наибольшее кол-во друзей в наш канал по вашей реферальной ссылке. Чем больше приведете людей, тем больше шансов выиграть крутые призы, о них подробнее ниже)

P.S. Всех приглашенных пользователей будем проверять вручную😈

Конкурс продлится до <b>19:00 28.04</b>. Торопись, призов на всех не хватит.
Кстати, о призах, вот же они:

<b>ПРИЗЫ 🎁</b>
— 1 место: 3 NFT + место в <b>Whitelist</b>
— 2-3 места: 2 NFT + место в <b>Whitelist</b>
— 4-7 места: 1 NFT + место в <b>Whitelist</b>
— 8-20 места: место в <b>Whitelist</b>
— Также ребята, которые привели хотя бы 1 человека, примут участие в розыгрыше трех NFT, 20 мест в <b>Whitelist</b> и 15 TON.

Люди, которых вы привели, должны оставаться подписчиками до конца конкурса, иначе они не будут засчитаны, поэтому советуем всем оставаться на своих местах, дальше будет еще интереснее)

<b>ИТОГИ:</b>
Вечер 28.04
Именно в это время вы узнаете, кто победил и кто получит заветные призы, приводите больше друзей, чтобы о нас узнало больше людей, а у вас было больше шансов победить)

Желаем всем удачи!
"""
subscribe_to_join = ""
subscribed_to_all = "✨ Поздравляем! Вы участвуете в конкурсе+розыгрыше от <a href=\"https://t.me/toncells\"><b>TonCells</b></a>."
already_registered = "Вы уже участвуете в конкурсе!"
missing_command = "Неверная команда!"

[bot.format_strings]
unsubscribed = "Вы отписались от канала @%s и больше не участвуете в конкурсе. Подпишитесь, чтобы опять принять участие."
friend_unsubscribed = "Ваш друг @%s отписался от канала @%s и больше не участвует в конкурсе. Пришлось забрать ваши 50 баллов :("
friend_subscribed_to_all = "Ваш друг @%s подписался на все каналы из условий и теперь участвует в конкурсе. А вы получили 100 баллов!"
points = "У вас %v баллов!"
personal_link = "Ваша персональная ссылка для приглашения: \n\nhttps://t.me/%s?start=%d"
you_were_invited = "Вы были приглашены другом @%v!\n\n%s"

[bot.buttons]
invite = "Пригласить"
points = "Баллы"
rating = "Рейтинг"
info = "Инфо"

[database]
address = "127.0.0.1"
port = ":5432"
name = "ton_bot"
username = "user"
password = "passwd"
scheme = "postgres"
